### ISSUE TITLE
Ramps 1.7 and DUE

### ISSUE THREAD

**Issue by boelle** [MarlinFirmware/Marlin#11655]
Hi all

@MrAlvin havde made the next version of the Ramps board, but I have some issues getting it to work. Just reading temps and getting a response from M119 is royal pain in the rear.

He made a test program which is here: https://github.com/MrAlvin/RAMPS_1.7/tree/master/Arduino%20test%20sketches/test%20everything/ee_ana_blink_end_step

Everything works fine with that

He also for dev purpose made a fork with settings ready to go: 

https://github.com/MrAlvin/Marlin/tree/bgfx-20x-R17-dev

That one does not work. No temps and no response from M119, M502 does not give a response either.

We have tried both arduino ide 1.8.6 and 1.9 and platform io

Anyone that can help us spot what is going wrong for us?

**Comment by boelle** [comment]
@kabelfrikkler

got an email that you had made an reply but its gone... did you regret?

**Comment by workheart** [comment]
change line nr 24 `env_default = megamega2560`
in platformio.ini
to` env_default = DUE`
it compiled without error in platformio :-) 
@boelle, i was to fast but now it worked

**Comment by boelle** [comment]
its not compile errors that are the problem

and yes i did change that line in platformio.ini

the problem is when the code is uploaded to the board.... nothing works

**Comment by boelle** [comment]
btw... i understand both english and german (and danish) if that helps

not sure about @MrAlvin  but he understands English and danish :-)

**Comment by workheart** [comment]
hard to find without the board, guess you have to wait for someone with more DUE expertise,
what does Work on the new board? how many did you make?

**Comment by boelle** [comment]
we just have a few prototypes

everything works with the test program, but not with marlin

is it @Bob-the-Kuhn that does a lot of 32 bit stuff? or maybe @Wurstnase ?

**Comment by boelle** [comment]
i know that @MagoKimbra did some due stuff once but not sure if he is still active and throw some light on it

**Comment by MrAlvin** [comment]
As I have more test tools and options available, I did further testing, and I got the bed and hot-end temperatures to work, by switching bed pin from (analog) pin 5 to pin 7. Pin 7 is marked T3 on the PCB.  Pin 5 is marked Bed on the PCB. 

While things were running (meaning; hot-end and bed were being heated), I also tested the volt reading (using a multimeter) for analog pins 5, 6 and 7.  And with Marlin running, analog pin 5 was stuck at the same voltage, despite physical temperatures were changing.

When running my test programs (as linked to above by Boelle), analog pins 5, 6 and 7 all works, and the multimeter shows voltage changes for all three pins.  With my simple test programs running, analog pin 5  is NOT stuck, and the voltage changes, when the physical temperatures change. 

So a work-around has been identified, but it would still be nice if analog pin 5 could  be used as; an analog pin.

**Comment by tonnico** [comment]
It's probably a year ago that I've compiled the latest Marlin with PlatformIO on my Due. I had no issues. I need to remove some libs that time, because that didn't worked in the past with the Due. 

On the SAM3X is pretty simple to use the analog inputs programmatically. You don't need any DMA or other things. I didn't check the Marlin code, but probably the analog pin 5 is used also somewhere as digital pin? Please check the numbers. Digital pins and analog pins have different numbers but could share the same one.

**Comment by boelle** [comment]
but would using analog pin and same number digital (analog 5 and digital 5) explain why it does not respond to commands? ie sending M119 returns no reply, its like marlin is dead :-)

**Comment by MrAlvin** [comment]
@Wurstnase  Ah, yes.  That was indeed the problem. I had not connected the dots: A5 =D59. And D59 had been typed, where it should have been D58. Typo is now fixed, and analog 5 (bed) is reporting temperatures. 
Thank you :-)

**Comment by boelle** [comment]
i will have a go too then :-D

**Comment by boelle** [comment]
@MrAlvin do you also get a response when you send M119

me still unzipping

**Comment by MrAlvin** [comment]
hmmm.... M119 is on a different issue. But I will do some testing, and let you know.  Ok?

**Comment by MrAlvin** [comment]
This is what I have found: 
With standard setting in configuration.h, you need to use NC (normal close) end-stops, to get a "trigger response" on M119.
Otherwise set end-stops to true, like: "X_MIN_ENDSTOP_INVERTING true", when using NO (normal open) end-stops.
I have now changed my configuration.h to use NO end-stops.

**Comment by boelle** [comment]
hehe, the reason why i asked is that before i could not get any response from anything :-)

ie M119 would not reply if endstops was triggered or not

M114 shoould tell you where the board thinks the nozzle is, always 0,0,0 after reset

**Comment by boelle** [comment]
yaaa :-D

i get response from both M119 and M114

and i can control bed heating and nozzle heating

big thanks to @Wurstnase so far

**Comment by boelle** [comment]
The only thing i have not been able to test with success are:

Fan on with M106 and off with M107, there is no response on serial output and no reaction on board

the board has an extra fan connector on digital 8, no reaction with M42 P8 S255 or  M42 P8 S0, not on board or serial

X max does not change status

my printer is the only one that has drivers that run on 3.3V logic and that one is doing a print so will have to wait testing the steppers

**Comment by workheart** [comment]
I recommend the m m43 t option to triger pins for dwbuging purpose. it has the possibility to test lets say 10 pins and check with a multimeter if the pin: 5 is wher you think it is it tells you what is the internal and the analog and the external pin name etc. Verry handy on board dev.http://marlinfw.org/docs/gcode/M043-T.html

**Comment by boelle** [comment]
i will try that

how to debug output? also with M43?

**Comment by workheart** [comment]
Yes its easy follow the marlin docu,
http://marlinfw.org/docs/gcode/M043-T.html  set the time to .. 15seconds
that you have terminal output what pin gets triggerd (it switches high low
high low...) And informatin on the pins,
I do disconect my drivers etc so i can probe eerything else if it is not
where or what i expected. If i than dont find it i run the code without the
shield, .... On step at a time :) its time consuming but it helps trouble
Shooting
Ther is no debuging information per se in the output,

**Comment by MrAlvin** [comment]
Hi boelle,

I am today working to get the standard (5V) LCD displays up and running with the 3V Due.  I have made a universal bi-directional adapter board, so all pins on aux3 and aux4 are level shifted  between 3V and 5V. This should allow for any existing display to be able to be used with this RAMPS 1.7 + Due. 

When this is done (or when I take a break from the LCD stuff) , I will look into the other issues you mention, like: 

- Fan on with M106 and off with M107, the board has an extra fan connector on digital 8, but no reaction with M42 P8 S255 or M42 P8 S0, not on board or serial

- X max does not change status. 

- my printer is the only one that has drivers that run on 3.3V logic and that one is doing a print so will have to wait testing the steppers. 
A comment: so far the steppers I have tested with (A4988 and DRV8825) have been working like usual.

**Comment by boelle** [comment]
strange... i use M43 W to tell me if a pin changes state

nothing happens when i short the X max connector, and as i understand things it should at least tell me a pin number that changes state

will try M43 I to get state of all pins and see if one of them changes

**Comment by boelle** [comment]
only pin 54 changed

```
PIN: 00        RXD                                    Input  = 1
PIN: 01        TXD                                    Input  = 1
PIN: 02        E_MUX0_PIN                             Input  = 1
.              X_MAX_PIN                              Input  = 1
PIN: 03        X_MIN_PIN                              Input  = 1
PIN: 04        SERVO0_PIN                             Input  = 1
PIN: 05        SERVO1_PIN                             Input  = 1
PIN: 06        E1_CS_PIN                              Input  = 1
.              FIL_RUNOUT_PIN                         Input  = 1
.              SERVO2_PIN                             Input  = 1
.              Z2_CS_PIN                              Input  = 1
PIN: 07        SERVO3_PIN                             Input  = 1
PIN: 08        E0_AUTO_FAN_PIN                        PWM = 0
PIN: 09        FAN_PIN                                PWM = 0
.              RAMPS_D9_PIN
PIN: 10        HEATER_BED_PIN                         Output = 0
.              RAMPS_D8_PIN                           Output = 0
PIN: 11        HEATER_0_PIN                           Output = 0
.              RAMPS_D10_PIN                          Output = 0
PIN: 12        PS_ON_PIN                              Output = 0
PIN: 13        LED_PIN                                Input  = 0
PIN: 14        <unused/unknown>                       Input  = 1
PIN: 15        E_MUX1_PIN                             Input  = 1
.              Y_MAX_PIN                              Input  = 1
PIN: 16        LCD_PINS_RS                            Output = 0
PIN: 17        LCD_PINS_ENABLE                        Output = 0
PIN: 18        <unused/unknown>                       Input  = 1
PIN: 19        E_MUX2_PIN                             Input  = 1
.              Z_MAX_PIN                              Input  = 1
PIN: 20        <unused/unknown>                       Input  = 1
PIN: 21        <unused/unknown>                       Input  = 1
PIN: 22        E1_ENABLE_PIN                          Output = 0
.              Z2_ENABLE_PIN                          Output = 0
PIN: 23        LCD_PINS_D4                            Output = 0
PIN: 24        E1_STEP_PIN                            Output = 0
.              Z2_STEP_PIN                            Output = 0
PIN: 25        LCD_PINS_D5                            Input  = 1
PIN: 26        E1_DIR_PIN                             Output = 0
.              Z2_DIR_PIN                             Output = 0
PIN: 27        LCD_PINS_D6                            Input  = 1
PIN: 28        <unused/unknown>                       Input  = 1
PIN: 29        LCD_PINS_D7                            Input  = 1
PIN: 30        E0_ENABLE_PIN                          Output = 0
PIN: 31        BTN_EN1                                Input  = 1
PIN: 32        <unused/unknown>                       Input  = 1
PIN: 33        BTN_EN2                                Input  = 1
PIN: 34        E0_STEP_PIN                            Output = 0
PIN: 35        BTN_ENC                                Input  = 1
PIN: 36        E0_DIR_PIN                             Output = 0
PIN: 37        BEEPER_PIN                             Output = 0
PIN: 38        E0_CS_PIN                              Input  = 1
PIN: 39        <unused/unknown>                       Input  = 1
PIN: 40        MAX6675_SS                             Input  = 1
PIN: 41        KILL_PIN                               Input  = 1
PIN: 42        Y_CS_PIN                               Input  = 1
PIN: 43        <unused/unknown>                       Input  = 1
PIN: 44        <unused/unknown>                       Input  = 1
PIN: 45        <unused/unknown>                       Input  = 1
PIN: 46        X_CS_PIN                               Input  = 1
PIN: 47        <unused/unknown>                       Input  = 1
PIN: 48        Z_CS_PIN                               Analog in =     0
PIN: 49        SD_DETECT_PIN                          Input  = 1
PIN: 50        MISO_PIN                               Input  = 1
PIN: 51        MOSI_PIN                               Input  = 1
PIN: 52        SCK_PIN                                Input  = 1
PIN: 53        SDSS                                   Output = 0
.              SS_PIN                                 Output = 0
PIN: 54 (A 0)  <unused/unknown>   Analog in =   939   Input  = 1
PIN: 55 (A 1)  X_ENABLE_PIN                           Output = 0
PIN: 56 (A 2)  X_STEP_PIN                             Output = 0
PIN: 57 (A 3)  X_DIR_PIN                              Output = 0
PIN: 58 (A 4)  Y_ENABLE_PIN                           Output = 0
PIN: 59 (A 5)  TEMP_BED_PIN                           Input  = 1
PIN: 60 (A 6)  TEMP_0_PIN                             Input  = 1
PIN: 61 (A 7)  TEMP_1_PIN                             Input  = 1
PIN: 62 (A 8)  Y_STEP_PIN                             Output = 0
PIN: 63 (A 9)  Y_DIR_PIN                              Output = 0
PIN: 64 (A10)  Z_MIN_PROBE_PIN                        Input  = 1
PIN: 65 (A11)  <unused/unknown>   Analog in =  1023   Input  = 1
PIN: 66        <unused/unknown>                       Input  = 1
PIN: 67        Z_ENABLE_PIN                           Output = 0
PIN: 68        Z_STEP_PIN                             Output = 0
PIN: 69        Z_DIR_PIN                              Analog in =     0
PIN: 70        <unused/unknown>                       Input  = 1
PIN: 71        <unused/unknown>                       Input  = 1
PIN: 72        <unused/unknown>                       Input  = 1
PIN: 73        <unused/unknown>                       Input  = 1
PIN: 74        <unused/unknown>                       Input  = 1
PIN: 75        <unused/unknown>                       Input  = 1
PIN: 76        <unused/unknown>                       Input  = 1
PIN: 77        <unused/unknown>                       Input  = 0
PIN: 78        <unused/unknown>                       Input  = 1
```

with x max shorted it changes to
```
PIN: 54 (A 0)  <unused/unknown>   Analog in =   942   Input  = 1
```

**Comment by boelle** [comment]
With M43 I T S8 R5 W1000 i can get the extra fan connector make my voltmeter go from 0 to 12 and back

so it its on D8 but strange is that i cant change state with M42 P8 S255

**Comment by boelle** [comment]
ahh protected pin

SENDING:M42 P8 S255
Error:Protected Pin
[ERROR] Error:Protected Pin

now where is that set i dont know

**Comment by boelle** [comment]
the part cooling fan on D9 have a LEd and it blinks only very shortly and voltmeter is not fast enough

but if i put the voltmeter on the pin from the DUE is changes from 3.3V to 0V and back

D11 which is the nozzle/extruder heater does not react when i try to pulse it
Same for D10 which is the bed heater

Solved the mystery on X max for now... it does only pulse to 3.3V if i put voltmeter directly to pin on due, so there is a missing connection between due and shield on that pin

**Comment by boelle** [comment]
so i reheated the pin for D2 and now i cant get a response from M502 or M43 I T S2 R5 W1000. M119 and M114 is also non responsive

will take shield of and check pins ( again :-) )

**Comment by MrAlvin** [comment]
I have got M106 and M107 working now. For both P0 and P1 (Fan0-D10 and Fan1-D8)
To get it to work, a FAN_1_PIN definition was in need of being added to the pins_RAMPS_17.h file

I also corrected something about Bed pin assignment, that would otherwise have Bed pin as Fan0 pin.

I hope this helps.

**Comment by boelle** [comment]
oki... will upload the test sketch to confirm everything still works

then i will download the new pins file and see if that solved it

**Comment by boelle** [comment]
M106 P0 works but not M106 P1

M42 P8 S255 does not work either

**Comment by boelle** [comment]
tried With M43 I T S8 R5 W1000 and it can pulse the output

the strange thing is that it can stop repsonding to the command 

normally when the command is issued serial output says its pulsing and what the pin is used for, but that can stop and then not even a reset will help

somethings is very fishy :-D

**Comment by AnHardt** [comment]
[pin_is_protected()](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Marlin_main.cpp#L7294-L7302)
[#define SENSITIVE_PINS](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/pins.h#L778-L786
)

**Comment by AnHardt** [comment]
[M42](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/Marlin_main.cpp#L7310-L7342) Have a look at the special handling for the fans. **If** a **soft** PWM is running at that pin the just written value is  overwritten by that a moment later. Could (should?) be similar for the heaters. (Then potentially DANGEROUS! - but not more than with a hardware PWM)

**Comment by AnHardt** [comment]
Setting the PWM for the heaters to a value that will stay, is much more complex. The PWM value is permanently set by the heater PDI. Bang bang and limit switching would also overwrite the pin state immediately.

**Comment by AnHardt** [comment]
For a test of the heater pins better just use the heater commands.
Maybe we can add a warning to M42.

**Comment by AnHardt** [comment]
The heaters are never really **OFF** - except after a kill.
If the environment temperature would be below zero, the heaters would try to heat to zero - provided MINTEMP is not biting before.

**Comment by boelle** [comment]
Sorry old man here felt asleep in front of pc

have 2 due's from arduino.cc and one was still in box so took that one and flashed marlin to it

even M502 gets no response so something is wrong

**Comment by boelle** [comment]
now trying to download again from https://github.com/MrAlvin/Marlin/tree/bgfx-20x-R17-dev and this time make no changes to config to see if something changes

if it works it must be my config that is screwed up somehow, even thou i doubt it since it worked a few hours ago

**Comment by AnHardt** [comment]
A naked DUE has no EEPROM - just an emulation (that must be activated?)

**Comment by boelle** [comment]
there is an eeprom on the shield/board :-)

**Comment by boelle** [comment]
but that is the only thing i will do, put on the shield and upload code as it is on github

**Comment by boelle** [comment]
a strange thing, when i upload from platform io i get this

Forcing reset using 1200bps open/close on port COM13
Uploading .pioenvs\DUE\firmware.bin
No device found on COM13
*** [upload] Error 1

but windows can see the board fine

will try a few times

**Comment by boelle** [comment]
managed to upload the code

still no response from M502, not from M119 or M114 either

using pronterface and the temp does not update

will try the test program again

**Comment by boelle** [comment]
yep, test program confirms everything working

hmm... maybe its best to get some good sleep

**Comment by boelle** [comment]
yep time for some sleep to me

managed to flash the copy of marlin linked in first post and for some reason that does not work for me

**Comment by boelle** [comment]
output from serial:
```
Connecting...
start
Printer is now online.
echo:PowerUp
Marlin bugfix-2.0.x
echo: Last Updated: 2018-01-20 | Author: (none, default config)
echo:Compiled: Aug 29 2018
echo: Free Memory: 86628  PlannerBufferBytes: 1408
echo:Hardcoded Default Settings Loaded
echo:  G21    ; Units in mm (mm)
echo:  M149 C ; Units in Celsius
echo:Filament settings: Disabled
echo:  M200 D3.00
echo:  M200 D0
echo:Steps per unit:
echo:  M92 X80.00 Y80.00 Z4000.00 E500.00
echo:Maximum feedrates (units/s):
echo:  M203 X300.00 Y300.00 Z5.00 E25.00
echo:Maximum Acceleration (units/s2):
echo:  M201 X3000 Y3000 Z100 E10000
echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P3000.00 R3000.00 T3000.00
echo:Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
echo:  M205 B20000 S0.00 T0.00 X10.00 Y10.00 Z0.30 E5.00
echo:Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:Material heatup parameters:
echo:  M145 S0 H180 B70 F0
echo:  M145 S1 H240 B110 F0
```

what i note is that it loads hard coded default so it has no contact with eeprom on shield

also temp graphs does not update and it does not repond to commands

[https://i.imgur.com/cVMkbQO.png](url)

**Comment by MrAlvin** [comment]
There is indeed an eeprom on the board, but to use it, it must first be activated.  

If you look at the top of the configuration.h file on https://github.com/MrAlvin/Marlin/tree/bgfx-20x-R17-dev you will see a list of notes and comments about what has been done, and what needs to be done/tested, in order to get the correct settings in Marlin activated, so all things on the board will eventually end up working. 

On the ToDo list/"changes that needs to be done", is: eeprom, SDcard, LCD displays. But more details will also need to be tested. 
And I will say that you are doing a great job testing, and discovering which commands needs attention, and adjustments in various files of the settings in Marlin, so the hardware and the firmware will eventually come together.  So please keep up the good work. 
It might however help to lower your level of frustration, to remember that right now is a phase of prototype and discovery. Okay? 

But still, please keep up the good work, with the testing of gcodes. The testing is greatly appreciated. Okay?

**Comment by MrAlvin** [comment]
I have now activated eeprom in configuration.h, and tested that it works. 

I used M503 to see all active settings, then M500 to store in eeprom. 
Then tested by changing M204 to different numbers, M503 to verify. Then M500 to store in eeprom.  
Then reset button, to restart Due. 
Then M503 to see that eeprom values were used at boot. 
Then M502 to reset to hardcoded defaults, and M503 to verify that M204 changed back to hardcoded default. 
Then M501 to read from eeprom, and M503 to verify that M204 had changed. 

And it worked.

**Comment by boelle** [comment]
morning

yep i know its still prototype, what made me maybe just a little frustrated is that due to double checking i started to think that my DUE's was bad

but then again why should 2 be bad at the same time

so i will try and relax more :-D

it was very late before i got to sleep so it will be a few hours yet until i can test the latest changes, still feel lile a zombie after only 5 hours of sleep

**Comment by boelle** [comment]
just flashed the firmware again, no changes done to me other than editing platformio.ini to say: env_default = DUE

when connecting i get: 

start
echo:PowerUp
Marlin bugfix-2.0.x
echo: Last Updated: 2018-01-20 | Author: (none, default config)
echo:Compiled: Aug 29 2018
echo: Free Memory: 86620  PlannerBufferBytes: 1408
Error:EEPROM CRC mismatch - (stored) 37377 != 18576 (calculated)!
[ERROR] Error:EEPROM CRC mismatch - (stored) 37377 != 18576 (calculated)!

echo:Hardcoded Default Settings Loaded

**Comment by boelle** [comment]
trying to load defaults do not work:

>>>M502
SENDING:M502

will try the other due to see if that changes anything. if not i will try and take off the shield

even without the eeprom it should respond to M502

**Comment by boelle** [comment]
with shield on it does not repsond to M502

without it does

its the same on both due's

**Comment by workheart** [comment]
Well, with shield ther is eprom and without shield ther is none, that is
reasonable. I would start with some arduino eeprom test\example script test
if its marlin or board related.

Bo Herrmannsen <notifications@github.com> schrieb am Mi., 29. Aug. 2018,
11:01:

**Comment by boelle** [comment]
the test program in the first post tests everything on the shield.... including the eeprom

and everything works fine with the test program

**Comment by boelle** [comment]
some more sad news

i have been in contact with arduino support and found out that both usb ports work perfectly fine if no shield  is on

if the shield is on then the navtive port stops working (does not show up in device manager) and the programming port shows up but when trying to program it will say: No device found on COM13

its the same for both due's i have only difference is the serial port number

**Comment by MrAlvin** [comment]
About eeprom. 

When you first load a firmware, the eeprom is not being changed, nor loaded with anything.
This is why you first do M503, to see all the default settings, as set in the config files.
 
Then you store those settings into eeprom with **M500**.  
This is the first time that the eeprom contains any information, useful to the Marlin firmware. 

After this you can use M502 to see what is stored in eeprom. 

You need to use the same procedure whenever a newer firmware is storing new variables in eeprom. Not different values, but different variables, or variables in a different order. 
Marlin has a way to signal this change, in storing new variables, or in a different order, in eeprom, but I do not right now know how this method works.   It used to be that the MACHINE_UUID would be used (possibly many years ago) but I imagine that a better method is used today. It could be a CRC check. 

And this could be why, when you first load a firmware, with eeprom enabled, you get a CRC error. Because the eeprom would contain whatever the little test programs, I have made, would leave in the eeprom. The test program basically leaves  ten numbers in sequence in the first ten positions of the eeprom, and this is definitely different from what marlin would store in the first ten bytes of eeprom. 

I hope this sequence of doing eeprom (M503, M501, M502), will result in something useful to you.

**Comment by MrAlvin** [comment]
About com ports going wrong. 

I have experienced similar situations in the past, and in windows I have fixed them by un-installing the driver associated with that com port. 

One challenge about un-installing a driver (in windows) to a com port that is not working, is that the com port does not show up in the device manager list - until you find a way to have hidden ports shown, that is.  Then the hidden ports will be shown in lighter gray. 

In the windows 10 I have on my machine, there is a menu option for device manager, when right clicking on the start button. 
Otherwise (again on my windows10 version) it is possible to do the search magnifying glass, and type in "device manager", and then a clickable link appears. 

In device manager, chose menu:"view", and select "show hidden devices". 
Then go to "ports (com+lpt)", and expand the list. This should now show all the com ports that have ever been set up on you computer.  
By right clicking on a com port, it becomes possible to select "Uninstall device". 

Next time the device is plugged in, then a new com port is set up, for that particular serial port/usb device. 

I hope this will help you fix the com port situation. 

Com port troubles can some times arise when too many different environments try to access a particular com port at the same time. 
For 3D printers then,  the Arduino interface, the host software (I user Repetier host), and "platform.io", might all try to access the same com port at the same time, and this can, at times, cause software hick-ups, at the driver level.  And most of the time this can be fixed by removing the com device, and hopefully this will also reset things within each of the environments. 

If you use windows 7, there might be an additional setting that needs added, in order to have the device manager show ALL hidden devices. As I recall, an environment variable needs to be set. 

But hopefully your device manager will easily show the hidden com ports, and hopefully it will allow for new registration of the com ports on your Due's.

**Comment by boelle** [comment]
will try to uninstall both ports first

and yes using winddows 10 home 64 bit (cheapskate)

**Comment by boelle** [comment]
removed all hidden items under ports and under usb

still the same and have sent you some screenshots

could there be a short or something on the board that would make this happen? if so where should i look?

**Comment by boelle** [comment]
a note to everyone that is interested, i flashed the test program linked in the first post and everything that the program test works

and i spent the better part of an hour emailing with arduino support to make sure it was not the due or cables that was at fault

dinner time but after it time to get the magnifying glass out and eyeball every little solder joint 

what are the chances that something in the copy of marlin linked in the first post has a stupid little mistake that makes the show stop?

**Comment by MagoKimbra** [comment]
Hi, I read only now ...
You can try the basic configuration with the 1.7 ramps with MK4duo, the part of the displays is not yet complete. But a test only serial engines and temperature you can try.
https://marlinkimbra.it/configurator/v4_3_6/firmware_configurator.php
Choice ARDUINO DUE processor and RAMPS 1.7 HFB.

**Comment by MrAlvin** [comment]
Hi @MagoKimbra , thank you for making this shield selectable on the MK4Duo configuration list. 
As soon as I get the last few details working with Marlin 2.0, then I will do tests with the MK4Duo.

**Comment by boelle** [comment]
Morning everyone..

@MagoKimbra 

i opened the configurator and just selected due and ramps 1.7 and then downloaded, got some compile errors and can see they are spi related. It happens both with IDE 1.8.5 and 1.9:
```
In file included from sketch\src\platform\HAL_DUE\../../../src/platform/platform.h:41:0,

                 from sketch\src\platform\HAL_DUE\../../../MK4duo.h:112,

                 from sketch\src\platform\HAL_DUE\HAL_spi.cpp:44:

sketch\src\platform\HAL_DUE\HAL_spi.cpp: In static member function 'static void HAL::spiBegin()':

sketch\src\platform\HAL_DUE\../../../src/inc/conditionals_post.h:301:21: error: 'SPI_FULL_SPEED' was not declared in this scope

   #define SPI_SPEED SPI_FULL_SPEED

                     ^

sketch\src\platform\HAL_DUE\../../../src/platform/HAL_DUE/communication.h:104:57: note: in definition of macro 'SERIAL_VAL'

 #define SERIAL_VAL(val, ...)                (Com::print(val, ## __VA_ARGS__))

                                                         ^

sketch\src\platform\HAL_DUE\../../../src/platform/HAL_DUE/communication.h:123:49: note: in expansion of macro 'SERIAL_MV'

 #define SERIAL_EMV(msg, val, ...)           do{ SERIAL_MV(msg, val, ## __VA_ARGS__); SERIAL_EOL(); }while(0)

                                                 ^

sketch\src\platform\HAL_DUE\HAL_spi.cpp:159:7: note: in expansion of macro 'SERIAL_EMV'

       SERIAL_EMV("SPI_SPEED:", SPI_SPEED);

       ^

sketch\src\platform\HAL_DUE\HAL_spi.cpp:159:32: note: in expansion of macro 'SPI_SPEED'

       SERIAL_EMV("SPI_SPEED:", SPI_SPEED);

                                ^

In file included from sketch\src\platform\HAL_DUE\../../../MK4duo.h:106:0,

                 from sketch\src\platform\HAL_DUE\HAL_spi.cpp:44:

sketch\src\platform\HAL_DUE\../../../src/inc/conditionals_post.h:301:21: error: 'SPI_FULL_SPEED' was not declared in this scope

   #define SPI_SPEED SPI_FULL_SPEED

                     ^

sketch\src\platform\HAL_DUE\HAL_spi.cpp:160:15: note: in expansion of macro 'SPI_SPEED'

       spiInit(SPI_SPEED);

               ^

exit status 1
Error compiling for board Arduino Due (Programming Port).
```

**Comment by MagoKimbra** [comment]
Yes i found this error, one moment...

**Comment by boelle** [comment]
no stress, its weekend :-)

any chance you are good with hardware also? i have a strange issue with the ramps 1.7 board i got from @MrAlvin 

i can only flash code with the shield off the due, but his test program shows that everything works

the issue is that with the shield off both usb ports work, with the shield on the native port cant be recognised by windows, and i cant flash via the programming port

**Comment by MagoKimbra** [comment]
Ok fixed...
I made the change to SPI_SPEED last night and I did not realize that if the SD is not defined the value of SPI_FULL_SPEED are not defined.

**Comment by boelle** [comment]
it can happen to all of us when its late and you should be sleeping

are you good with hardware also?

**Comment by MrAlvin** [comment]
A few more details about boelle's hardware troubles. 
Yesterday we looked into many details, and to his words about not being able to flash via the programming port I would add: 
-It is possible to select the port in Arduino IDE, but when the process is about to upload, then an error like "No device found on COM4, An error occurred while uploading the sketch"  is shown.  

I can replicate this exact error message if I: plug-in my Due, select the port, get ready to compile, un-plug the Due, and then compile. 

If the com port is occupied by, lets say Repetier Host,  when Arduino IDE wants to upload after a compile, a very different error message is shown, with details that indicates that the com port is occupied. 

-Further more.....  it is possible to get responses from boelle's Due, by using the Arduino IDE Monitor. 

So, if Marlin is loaded (with-out the shield mounted), and the shield then gets mounted, it is possible to get/see the first response from the boot-up of Marlin, like: 
"start
echo:PowerUp
Marlin bugfix-2.0.x

echo: Last Updated: 2018-01-20 | Author: (none, default config)
echo:Compiled: Aug 31 2018
echo: Free Memory: 84724  PlannerBufferBytes: 1408
Error:EEPROM CRC mismatch - (stored) 37377 != 18576 (calculated)!
echo:Hardcoded Default Settings Loaded"

I this case the com-port is operational, while the shield is mounted. 

I must say, this thing, where the programming com port comes and goes, has got me baffled.

**Comment by boelle** [comment]
--If the com port is occupied by

that was not the case

--Further more..... it is possible to get responses from boelle's Due,

that is not the complete response, there should be a long list of settings etc

--, has got me baffled.

you are not alone

**Comment by boelle** [comment]
@MagoKimbra 

success, but not temp, might be because i have removed all jumper yesterday when testing
```
start
Printer is now online.
Info:PowerUp
Echo:MK4duo_4.3.6
Echo:Last Updated: Sep  1 2018 10:19:53 | Author: (none, default config)
Echo:Compiled: Sep  1 2018
Echo:Free Memory: 88264 PlannerBufferBytes: 2688
Echo:Factory Settings Loaded
Config:
  G21    ; Units in (mm)
Config:Steps per unit:
Config:  M92 X80.000 Y80.000 Z4000.000 T0 E625.000
Config:Maximum feedrates (units/s):
Config:  M203 X300.000 Y300.000 Z2.000 T0 E100.000
Config:Maximum Acceleration (units/s2):
Config:  M201 X3000 Y3000 Z50 T0 E3000
Config:Acceleration (units/s2): P<print_accel> V<travel_accel> T* R<retract_accel>:
Config:  M204 P3000.000 V3000.000 T0 R10000.000
Config:Advanced variables: B<min_segment_time_us> S<min_feedrate> V<min_travel_feedrate>:
Config: M205 B20000 S0.000 V0.000
Config:Jerk: X<max_xy_jerk> Z<max_z_jerk> T* E<max_e_jerk>:
Config: M205 X10.000 Y10.000 Z0.400 T0 E5.000
Config:Heater Sensor parameters: H<Heater> P<Pin> A<R25> B<BetaK> C<Steinhart-Hart C> R<Pullup> L<ADC low offset> O<ADC high offset>:
Config:  M305 H0 P6 A100000.0 B4092.0 C0.0000000000 R4700.0 L0 O0
Config:Heater parameters: H<Heater> P<Pin> A<Pid Drive Min> B<Pid Drive Max> C<Pid Max> L<Min Temp> O<Max Temp> U<Use Pid 0-1> I<Hardware Inverted 0-1>:
Config:  M306 H0 P11 A40 B230 C255 L5 O275 U1 I0
Config:Heater PID parameters: H<Heater> P<Proportional> I<Integral> D<Derivative>:
Config:  M301 H0 P40.000000 I7.000000 D60.000000
Config:Fans: P<Fan> U<Pin> L<Min Speed> F<Freq> I<Hardware Inverted 0-1> H<Auto mode> :
Config:  M106 P0 U10 L0 F250 I0
Config:Fans: P<Fan> U<Pin> L<Min Speed> F<Freq> I<Hardware Inverted 0-1> H<Auto mode> :
Config:  M106 P1 U8 L0 F250 I0 H0
Config:Stepper Direction:
Config:  M569 X0 Y0 Z0 T0 E0
Config:Stepper driver control:
Config:  M569 D0 P0 R500000
```

**Comment by MrAlvin** [comment]
@boelle 
"--If the com port is occupied by
that was not the case"
No, this was not a response at you computer, this was something I tested, to see what kind of respons the IDE would give if the com port was occupied.  In order to eliminate an option.  To eliminate the possibility that the ""No device found on COM4, An error occurred while uploading the sketch" message could also happen if the com port was take by some other program.

**Comment by MrAlvin** [comment]
@boelle  About the no temp while testing the MK4Duo, and no jumpers. 

Temperature gets its power from the Vcc rail, which is linked to the "Arduino IO" pin, so no jumpers are needed in order to power the temperature hardware.

**Comment by MagoKimbra** [comment]
The pin that controls is pin 6 for the sensor.
Config: M305 H0 P6 A100000.0 B4092.0 C0.0000000000 R4700.0 L0 O0
Are we sure the sensor is attached to the right pin?

**Comment by boelle** [comment]
```
start
Printer is now online.
Info:PowerUp
Echo:MK4duo_4.3.6
Echo:Last Updated: Sep  1 2018 10:19:53 | Author: (none, default config)
Echo:Compiled: Sep  1 2018
Echo:Free Memory: 88264 PlannerBufferBytes: 2688
Echo:Factory Settings Loaded
Config:
  G21    ; Units in (mm)
Config:Steps per unit:
Config:  M92 X80.000 Y80.000 Z4000.000 T0 E625.000
Config:Maximum feedrates (units/s):
Config:  M203 X300.000 Y300.000 Z2.000 T0 E100.000
Config:Maximum Acceleration (units/s2):
Config:  M201 X3000 Y3000 Z50 T0 E3000
Config:Acceleration (units/s2): P<print_accel> V<travel_accel> T* R<retract_accel>:
Config:  M204 P3000.000 V3000.000 T0 R10000.000
Config:Advanced variables: B<min_segment_time_us> S<min_feedrate> V<min_travel_feedrate>:
Config: M205 B20000 S0.000 V0.000
Config:Jerk: X<max_xy_jerk> Z<max_z_jerk> T* E<max_e_jerk>:
Config: M205 X10.000 Y10.000 Z0.400 T0 E5.000
Config:Heater Sensor parameters: H<Heater> P<Pin> A<R25> B<BetaK> C<Steinhart-Hart C> R<Pullup> L<ADC low offset> O<ADC high offset>:
Config:  M305 H0 P6 A100000.0 B4092.0 C0.0000000000 R4700.0 L0 O0
Config:Heater parameters: H<Heater> P<Pin> A<Pid Drive Min> B<Pid Drive Max> C<Pid Max> L<Min Temp> O<Max Temp> U<Use Pid 0-1> I<Hardware Inverted 0-1>:
Config:  M306 H0 P11 A40 B230 C255 L5 O275 U1 I0
Config:Heater PID parameters: H<Heater> P<Proportional> I<Integral> D<Derivative>:
Config:  M301 H0 P40.000000 I7.000000 D60.000000
Config:Fans: P<Fan> U<Pin> L<Min Speed> F<Freq> I<Hardware Inverted 0-1> H<Auto mode> :
Config:  M106 P0 U10 L0 F250 I0
Config:Fans: P<Fan> U<Pin> L<Min Speed> F<Freq> I<Hardware Inverted 0-1> H<Auto mode> :
Config:  M106 P1 U8 L0 F250 I0 H0
Config:Stepper Direction:
Config:  M569 X0 Y0 Z0 T0 E0
Config:Stepper driver control:
Config:  M569 D0 P0 R500000
```
temp 110, but this is without the shield on

i will put on the shield and connect sensors to both bed and hotend

**Comment by boelle** [comment]
Connecting...
start
Printer is now online.
Info:PowerUp
Echo:MK4duo_4.3.6
Echo:Last Updated: Sep  1 2018 10:19:53 | Author: (none, default config)
Echo:Compiled: Sep  1 2018
Echo:Free Memory: 88264 PlannerBufferBytes: 2688
Echo:Factory Settings Loaded
Config:
  G21    ; Units in (mm)
Config:Steps per unit:
Config:  M92 X80.000 Y80.000 Z4000.000 T0 E625.000
Config:Maximum feedrates (units/s):
Config:  M203 X300.000 Y300.000 Z2.000 T0 E100.000
Config:Maximum Acceleration (units/s2):
Config:  M201 X3000 Y3000 Z50 T0 E3000
Config:Acceleration (units/s2): P<print_accel> V<travel_accel> T* R<retract_accel>:
Config:  M204 P3000.000 V3000.000 T0 R10000.000
Config:Advanced variables: B<min_segment_time_us> S<min_feedrate> V<min_travel_feedrate>:
Config: M205 B20000 S0.000 V0.000
Config:Jerk: X<max_xy_jerk> Z<max_z_jerk> T* E<max_e_jerk>:
Config: M205 X10.000 Y10.000 Z0.400 T0 E5.000
Config:Heater Sensor parameters: H<Heater> P<Pin> A<R25> B<BetaK> C<Steinhart-Hart C> R<Pullup> L<ADC low offset> O<ADC high offset>:
Config:  M305 H0 P6 A100000.0 B4092.0 C0.0000000000 R4700.0 L0 O0
Config:Heater parameters: H<Heater> P<Pin> A<Pid Drive Min> B<Pid Drive Max> C<Pid Max> L<Min Temp> O<Max Temp> U<Use Pid 0-1> I<Hardware Inverted 0-1>:
Config:  M306 H0 P11 A40 B230 C255 L5 O275 U1 I0
Config:Heater PID parameters: H<Heater> P<Proportional> I<Integral> D<Derivative>:
Config:  M301 H0 P40.000000 I7.000000 D60.000000
Config:Fans: P<Fan> U<Pin> L<Min Speed> F<Freq> I<Hardware Inverted 0-1> H<Auto mode> :
Config:  M106 P0 U10 L0 F250 I0
Config:Fans: P<Fan> U<Pin> L<Min Speed> F<Freq> I<Hardware Inverted 0-1> H<Auto mode> :
Config:  M106 P1 U8 L0 F250 I0 H0
Config:Stepper Direction:
Config:  M569 X0 Y0 Z0 T0 E0
Config:Stepper driver control:
Config:  M569 D0 P0 R500000

temp for extruder 113 and for bed 0

**Comment by boelle** [comment]
oh... i forgot to pick sensor type in configurator

but i still get this when i try to flash code with shield on

Sketch uses 98908 bytes (18%) of program storage space. Maximum is 524288 bytes.
No device found on COM4
An error occurred while uploading the sketch

**Comment by MagoKimbra** [comment]
Please give the command M105 X1 and read valor for ADC...
@MrAlvin Do you use 3.3v on the analog pin or do you use a 5v to 3.3 translator?

**Comment by boelle** [comment]
no response

Config:  M569 D0 P0 R500000
>>>M105 X1
SENDING:M105 X1
>>>M105 X1
SENDING:M105 X1

**Comment by boelle** [comment]
test program linked in first post works fine... i can get values from that

but its stange, i have to flash the code with shield off and then put shield on later

**Comment by MagoKimbra** [comment]
The board is blocked... Uhm why??

**Comment by boelle** [comment]
that is the strange thing, to flash code i have to take the board of

and with board on i dont get responses like normal

i have been looking the board very closely and i cant find any shorts or anything like that

@MrAlvin  hand soldered it so maybe there could be a short under a SMD resistor, 

but i dont know which ones to check

**Comment by boelle** [comment]
without shield:

>>>M105 X1
SENDING:M105 X1
ok T:113.15 /0 (8208) @:0

**Comment by AnHardt** [comment]
Please discuss MK4Duo over there. The details are not very interesting for Marlin - maybe the result.

**Comment by boelle** [comment]
right now i think we are discussing why there is a difference between shield on or off

not so much if its marlin or mk4duo

**Comment by AnHardt** [comment]
I hardly dare to say:
Usually a forgotten open host is blocking the connection.
But you are using Marlin since years and should know about that.

**Comment by boelle** [comment]
no open host here, 

as you say i have used 3d printers for many years now, marlin and repetier

you can almost say that what we are trying is to eliminate possible faults by trying out a lot of things

**Comment by boelle** [comment]
my bet is that there is something on the shield that partly blocks the usb ports 

my reason for saying that is that i can program the due from both ports when the board is off, and with the board on one of the ports stops working completely and the other is kind of stuck in that i dont get the full startup with config etc

with the test program i can get things like temp  etc

but i only got a copy of the boardlayout and no schematic. 

if there was a complete schematic i could have started to compare it to other boards and maybe found some possible faults

again remember i did not make the board i just got an prototype from @MrAlvin and trying to get it to work. it was handsoldered so there is the possible of a short under a resistor or capacitor, but iøm not that good of an expert and dont know where to look first

only thing i know is that the 5v rail and 3.3v rail on the due is working

**Comment by AnHardt** [comment]
Accidently installed Repetier Server?

**Comment by boelle** [comment]
nope

no repetier stuff on this laptop since i last reformatted it

**Comment by boelle** [comment]
to flash code with success i just need to take the shield off :-D

its where the next thing i would do is pulling my hair out and say funny sounds

**Comment by workheart** [comment]
watch a goog TV show frink a glass of wine and start probing pins, (okay there, a scematic would indeed be helpfull, i dont get confortabel wit the repositorry either,) start With Ground 12, etc and chekc for beeep on every pin, (with the board installed) if it beeps: look if its ground, if ther is resistance, check if the resistants matches the PCB layout. thats what I did on my endstop error (did not find it but found other problems)
EDIT: I recomend a Marcer (black red yelow for manual pin assignment GND +12 +5 +3.3 etc) and Firefly

**Comment by boelle** [comment]
and the missing schematic is also a problem for me because i dont know what probe results i should get

and since the firmware can run without the shield and ports show up in windows device manager it can only mean that there is something wrong with the board

and if you take in to account that i spent an hour with arduino support check that the due an usb cable is ok and that the arduino ide is not screwed up it can only be 2 things left

either the firmware itself or the board

the only way i can rule the firmware out and not using the shield is to probe the pins that control things like heaters and fans at full speed, a normal multimeter is not fast enough for the steppers.... yes i can probe the enable and direction pins, but not the step pin... but i would say that if i can confirm those work then i would start to look at the shield itself

sadly its my birthday tomorrow and i still have a few things left to prepare and then i also need some sleep, so it will not be before monday i can do any more testing
