### ISSUE TITLE
[BUG] since updating MCStepper V0.4.0 I no longer have access to my serial port

### ISSUE THREAD

**Issue by gauix4** [MarlinFirmware/Marlin#14253]
SKR 1.3 TMC5160s V1.0
since updating MCStepper V0.4.0 I no longer have access to my serial port

[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/3269833/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/3269834/Configuration_adv.txt)

**Comment by gloomyandy** [comment]
It seems this issue is being worked on here https://github.com/MarlinFirmware/Marlin/pull/14245

**Comment by teemuatlut** [comment]
I applied your configuration to fix_tmc5160_init (which I had rebased to bf-2.0.x).
Then I disabled any TMC drivers and updated the firmware on the SD card.
The board still froze.

I then checked out the unmodified branch and enabled a basic 4xTMC5160 based configuration with a few options. The board booted just fine.

For now I don't think your issue is with the TMC library.

I'll do some further digging making changes to your files and see what comes of it.
I'd suggest you re-do configuration and carefully **avoid** setting the max speeds to 900000.

**Comment by teemuatlut** [comment]
[Marlin issue 14253.zip](https://github.com/MarlinFirmware/Marlin/files/3278280/Marlin.issue.14253.zip)
Boot working config based on the provided files.

**Comment by boelle** [comment]
so this one is fixed?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by gauix4** [comment]
the problem has never been solved
this one still does not work
I simply find how to counter the problem but not solve it

**Comment by gauix4** [comment]
I just use the port
#define SERIAL_PORT 2 - 1
and it works
  but not the port
#define SERIAL_PORT_1 -1
it does not work

**Comment by boelle** [comment]
@gauix4 is the issue still there?

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.
