### ISSUE TITLE
[BUG] Pin number oversight for STM32F4x?

### ISSUE THREAD

**Issue by gnusenpai** [MarlinFirmware/Marlin#14890]
On my SKR Pro v1.1, trying to assign the PB5 pin results in the use of the PB4 pin instead. This is visible when using M43.

In the following file:
https://github.com/MarlinFirmware/Marlin/blob/2971b48a128662ab2f50a0a238aedfb64ec785d9/buildroot/share/PlatformIO/variants/BIGTREE_GENERIC_STM32F407_5X/variant.h#L111-L114
 
The PB4 and PB5 pins are set to the same number: 45. I am assuming this is an oversight because it causes issues with trying to use the PB5 pin, and the rest of the file is sequential. Setting the value of PB5 to 46 and viewing the pins again with M43 shows that it fixes this issue.

**Comment by tpruvot** [comment]
yep, seems a typo :) someone forgot to put glasses ?

**Comment by thisiskeithb** [comment]
See PR https://github.com/MarlinFirmware/Marlin/pull/14891

**Comment by thisiskeithb** [comment]
The fix has been merged.

**Comment by MangaValk** [comment]
My second extruder stopped working. Noticed in m122 it wouldn't activate the second extruder anymore. After this fix the second extruder does activate but is still not stepping. Guess there are more typos somewhere since it did work before

**Comment by boelle** [comment]
will close as this has been fixed with #14891, we can always reopen if the problem is still there
