### ISSUE TITLE
[BUG] LCD 2004 and Mightyboard showing weird characters in some menu

### ISSUE THREAD

**Issue by chepo92** [MarlinFirmware/Marlin#17514]
### Bug Description
I'm updating some mightyboards with stock LCD to marlin 2.0.5.3 and facing this issues:
In some points navigating the menu (eg. moving axes), there appears a weird "H" character in the LCD. 

Also in some parts it shifts one char position. 

### My Configurations
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/4468391/configs.zip)

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. Upload
2. Navigate through menu

**Expected behavior:** clear lcd without rare chars

**Actual behavior:** "H"

#### Additional Information
![IMG_20200412_172648029](https://user-images.githubusercontent.com/26207806/79098962-19ec2f80-7d31-11ea-97f2-ae3c1b73cc0e.jpg)

![IMG_20200412_172915523](https://user-images.githubusercontent.com/26207806/79098969-1c4e8980-7d31-11ea-8bb4-da8d2029bf49.jpg)

![IMG_20200412_172642521](https://user-images.githubusercontent.com/26207806/79098956-1658a880-7d31-11ea-9958-a50e09d1c811.jpg)

![IMG_20200412_172613287](https://user-images.githubusercontent.com/26207806/79098947-10fb5e00-7d31-11ea-8b66-020bb8cbee9c.jpg)

**Comment by ellensp** [comment]
Did you use official marlin? The reason I ask is the bug that places the last line one char left, I remember fixing a long time ago...  unless its regressed..      here https://github.com/MarlinFirmware/Marlin/issues/16566 Now confirmed this is still in current marlin
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/menu/menu_motion.cpp#L250

**Comment by chepo92** [comment]
I'll give a try to bugfix branch

**Comment by boelle** [comment]
@chepo92 is the issue still there ?

**Comment by chepo92** [comment]
> 
> 
> @chepo92 is the issue still there ?

Yes, I used bugfix a month ago and it was still present, I haven't done much debugging/reserach on it as is not critical

**Comment by boelle** [comment]
Please test the [bugfix-2.0.x branch](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) to see where it stands.

its updated daily and it might well be that your issue have been solved

**Comment by boelle** [comment]
Lack of Activity
This issue is being closed due to lack of activity. If you have solved the
issue, please let us know how you solved it. If you haven't, please tell us
what else you've tried in the meantime, and possibly this issue will be
reopened.

**Comment by chepo92** [comment]
Tested bugfix today, issue still present, any advice? I'm guessing is something related to LCD, timings or libraries

![IMG_20200711_162120503](https://user-images.githubusercontent.com/26207806/87233371-ae981500-c394-11ea-876a-a6cb066bd469.jpg)

![IMG_20200711_162138390](https://user-images.githubusercontent.com/26207806/87233372-afc94200-c394-11ea-9da3-6797f9311826.jpg)

![IMG_20200711_162249984](https://user-images.githubusercontent.com/26207806/87233374-b061d880-c394-11ea-8276-a61dc049bfe4.jpg)

![IMG_20200711_162309893](https://user-images.githubusercontent.com/26207806/87233375-b0fa6f00-c394-11ea-8761-2ea808cb04d6.jpg)

**Comment by chepo92** [comment]
I'm also having #17515 with this LCD and board
