### ISSUE TITLE
[FR] Support BTT SKR V1.1 with BTT mini 12864 V1.0

### ISSUE THREAD

**Issue by darranwil** [MarlinFirmware/Marlin#23334]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

BTT SKR V1.1 + BTT mini 12864 V1.0 compile fails with error: 'DOGLCD_A0' was not declared in this scope; did you mean 'DOGLCD_SCK'?

Same result with #define FYSETC_MINI_12864_2_1 or #define BTT_MINI_12864_V1.

Also having to add #define NEOPIXEL_PIN or compile fails.

### Bug Timeline

New?

### Expected behavior

Compiles successfuly

### Actual behavior

Compile fails with error: 'DOGLCD_A0' was not declared in this scope; did you mean 'DOGLCD_SCK'?

Same result with #define FYSETC_MINI_12864_2_1 or #define BTT_MINI_12864_V1.

Also having to add #define NEOPIXEL_PIN or compile fails.

### Steps to Reproduce

Downloaded latest bugfix.
Attempted to compile.

### Version of Marlin Firmware

2.0.9.2 busfix nightly

### Printer model

Generic 2 axis laser cutter.

### Electronics

SKR v1.1, 8825 steppers, BTT mini 12864 V1.0

**Comment by ellensp** [comment]
### Please note
 Not all screen work on all controllers out of the box, especially a new screen on a old board.

 ### IMPORTANT
You cannot just plug this lcd into that controller without re-wiring

Your motherboard board has these pin on exp1 and exp2
```
/**        ------                  ------
 *   1.30 |10  9 | 2.11      0.17 |10  9 | 0.15
 *   0.18 | 8  7 | 0.16      3.26 | 8  7 | 1.23
 *   0.15   6  5 | NC        3.25   6  5 | 0.18
 *     NC | 4  3 | NC        1.31 | 4  3 | RESET
 *    GND | 2  1 | 5V         GND | 2  1 | NC
 *         ------                  ------
 *          EXP1                    EXP2
 */
```
The neopixel is on EXP1_05_PIN for this LCD, but there is no connection on that pin.


Give this a try. It compiles and should work, but I cannot test it

Apply this diff to add support for this LCD, but you have to update   #define NEOPIXEL_PIN  the to actual pin you have wired it to. 

```DIFF
diff --git a/Marlin/src/pins/lpc1768/pins_BTT_SKR_V1_1.h b/Marlin/src/pins/lpc1768/pins_BTT_SKR_V1_1.h
index 48b178dab5..e05cf79dbd 100644
--- a/Marlin/src/pins/lpc1768/pins_BTT_SKR_V1_1.h
+++ b/Marlin/src/pins/lpc1768/pins_BTT_SKR_V1_1.h
@@ -117,8 +117,23 @@
   #if ENABLED(MKS_MINI_12864)
     #define DOGLCD_CS                      P2_06
     #define DOGLCD_A0                EXP1_07_PIN
-  #endif
+  #elif ENABLED(FYSETC_MINI_12864)
+    #define DOGLCD_CS                EXP1_08_PIN
+    #define DOGLCD_A0                EXP1_07_PIN
+    #define DOGLCD_SCK               EXP2_09_PIN
+    #define DOGLCD_MOSI              EXP2_05_PIN
+
+    #define LCD_BACKLIGHT_PIN              -1
 
+    #define FORCE_SOFT_SPI                      // Use this if default of hardware SPI causes display problems
+                                                //   results in LCD soft SPI mode 3, SD soft SPI mode 0
+
+    #define LCD_RESET_PIN            EXP1_06_PIN  // Must be high or open for LCD to operate normally.
+
+    #if ENABLED(FYSETC_MINI_12864_2_1)
+      #define NEOPIXEL_PIN                 P2_06
+    #endif
+  #endif                                        // FYSETC_MINI_12864
 #endif // HAS_WIRED_LCD
 
 //
```

**Comment by darranwil** [comment]
That did compile with no issues but I couldn't get the LEDs to work.  I guess I'll just swap this one with one of my regular 12864s on one of my printers which does have an SKR v1.4 board.

**Comment by Sonicboom247** [comment]
@ellensp could this be what is causing the issues with the other Fysetc mini 12864's? here is my config and i do not have
```cpp
#define DOGLCD_SCK
#define DOGLCD_MOSI

 #elif ENABLED(FYSETC_MINI_12864)
    #define DOGLCD_CS                       PB6
    #define DOGLCD_A0                       PC15

    //#define FORCE_SOFT_SPI                      // Use this if default of hardware SPI causes display problems
                                                //   results in LCD soft SPI mode 3, SD soft SPI mode 0

    #define LCD_RESET_PIN                   PB5   // Must be high or open for LCD to operate normally.
```
just tested with Force_Soft_SPI uncommented and the new EEPROM init reset change and still blank after reset....

**Comment by darranwil** [comment]
For me this issue is resolved(ish).  I ended up switching the BTT 12864 mini with the RepRap full graphic controller on another printer.

**Comment by Sonicboom247** [comment]
still not working for me with 2.0.9.3 or bugfix from last night, screen still freezes at marlin logo and then blank after reset.

**Comment by ellensp** [comment]
@Sonicboom247 that is indicative of marlin crashing, nothing to do with the lcd 
If it displays the logo, the screen is correct. Ie is your unrelated  Artillery Ruby conttroller.

**Comment by Sonicboom247** [comment]
@ellensp agreed, should i change the title on my issue to Marlin freezing then crashing after reset?

**Comment by Klabbob** [comment]
@Sonicboom247 What happens if you take out the SD card (if present) and reset the board? Does the screen then work?

**Comment by Sonicboom247** [comment]
@Klabbob , tried that last night after seeing the comments, same issue, i can go back to 9.1 with no issue

**Comment by ellensp** [comment]
Original poster has changed displays, so closing this
