### ISSUE TITLE
[BUG] Extruder not working when MKS 12864 Mini V3 enabled

### ISSUE THREAD

**Issue by Vit220** [MarlinFirmware/Marlin#24380]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

bugfix-2.1.x
BOARD_MKS_ROBIN_E3D_V1_1
MKS MINI12864 V3
If disable SDSUPORT extruder work

### Bug Timeline

new

### Actual behavior

extruder does not work

### Steps to Reproduce

1.BOARD_MKS_ROBIN_E3D_V1_1
2.MKS MINI12864 V3
3.Enable SDSUPORT

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

CoreXZ

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8948967/Configuration.zip)

**Comment by Bob-the-Kuhn** [comment]
Please try bugfix-2.1.x again.  An SD card fix was released via PR #24319 yesterday.  Maybe it fixed your problem.

**Comment by Salvogi** [comment]
Also I have the same problem with Marlin 2.1 while with Marlin 2.0 everything works correctly.
I have the following components.
- Makerbase MKS Robin E3D V1.1
- Makerbase MKS MINI12864 V3 LCD
- Makerbase MKS TMC2209 stepper driver

I tried Marlin 2.1.x bugfix downloaded from Marlin's website today, if I activate SDSUPPORT the extruder doesn't work, the driver is activated so I can't turn the motor with my fingers

These are my configuration files for the Marlin 2.1.x bugfix downloaded today (CONFIGURATION_H_VERSION 02010100)
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9105817/Configuration.zip)
.

**Comment by Salvogi** [comment]
I also tried the "Marlin Patched Source" version but the problem still persists.
Unfortunately I see some confusion in the download area of ​​the Marlin website. Before there were "release" and "bug fixs" versions now in the download area there are: 2.1 release, 2.1.x release, bugfix-2.1.x, 2.1.x Patched Source
and many others without any explanation of the differences.

**Comment by thisiskeithb** [comment]
Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

**Comment by Salvogi** [comment]
I tried version 2.0.9.4 and it always gives me the same error while version 2.0.9.2 works correctly so something happened during development of 2.0.9.3 or 2.0.9.4
[Configuration-2.0.9.4-not-work.zip](https://github.com/MarlinFirmware/Marlin/files/9113023/Configuration-2.0.94-not-work.zip)
[Configuration-2.0.9.2-work-fine.zip](https://github.com/MarlinFirmware/Marlin/files/9113031/Configuration-2.0.9.2-work-fine.zip)

**Comment by Salvogi** [comment]
> Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

Ok, now I'll try it tomorrow morning

**Comment by Salvogi** [comment]
> Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

I tried it, this one also gives the same error.

I also tried Marlin 2.0.9.3 and it also gives the same error.
So MKS MINI12864 V3 display with MKS Robin E3D V1.1 board works with Marlin up to version 2.0.9.2.

I tried to install Marlin on RAMPS with MKS MINI12864 V3.0 and A4988 driver and everything works correctly. Hence, the problem arises when using MKS Robin E3D V1.1 and MKS MINI12864 V3 at the same time.

The same problem was reported by other users here too https://github.com/makerbase-mks/MKS-Robin-E3-E3D/issues/165

**Comment by YAKICI-3D** [comment]
> Please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

Hello i have same issue on Marlin 2.0.9 and 2.1.0. My machine works perfectly on usb-pc connection but if i tried insert a sd card, extruder motor stuck suddenly and dont extrude. I contacted MKS factory for this problem, they said it's a firmware problem but no solution yet. I can working with this screen (MKS12864 V3.0) on mks gen L motherboard or i can working with mks robin e3 v1.1 with mkstft35 . Please help us Keith Bennett

**Comment by jesterhead82** [comment]
Works with todays Bugfix, but

-set -DDEFAULT_SPI=2, So Extruder Pins  #dont get misused, as  in #23715

- I revert #23282 so SD slot on MKS12864v3 Mini works




#https://github.com/MarlinFirmware/Marlin/issues/23715
#https://github.com/MarlinFirmware/Marlin/pull/23282

**Comment by YAKICI-3D** [comment]
Hello again, i try change.zip on Marlin 2.1.1 and problems solved. Extruder working and printer can work with sd card BUT printing with sd card my printer gets freezing randomly. How can i solve this problem ? Does changing SD_SPI speed settings work ? ( Half,quarter,eight)

**Comment by YAKICI-3D** [comment]
@ellensp 
@thisiskeithb

**Comment by pedroscsant** [comment]
I'm still having trouble with the latest 2.1.X (2010300)

With the SD attached, the extruder won't move. The files @ellensp provided in the #24882 seems to be the only solution for me, but the bug still exists on newer versions.

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10852502/Configuration.zip)

https://user-images.githubusercontent.com/115324096/221917702-d1c5b672-562a-43ce-862d-fb7bc6c20915.mp4


https://user-images.githubusercontent.com/115324096/221917722-6c651e6e-2467-4b57-8d4c-e75aba7e987e.mp4

**Comment by pedroscsant** [comment]
I've also revert to  2.0.9.2 as @Salvogi mentioned, can confirm it's working properly. Even with @ellensp "patch" it was misbehaving, losing steps ramdomly.
