### ISSUE TITLE
Cannot exit the "Move Axis" Menu

### ISSUE THREAD

**Issue by jlcdi** [MarlinFirmware/Marlin#3382]
Hi,

On Marlin 1.1.0-RC5, with a 12864 Reprap Discount Graphic LCD after entering, it is not possible to get out of the "Move Axis" menu.

Thanks for your help.

**Comment by thinkyhead** [comment]
@jlcdi Does this problem still exist in `RCBugFix`? We've been fixing bugs and updating code related to the LCD menus since `RC5` was released.

**Comment by jbrazio** [comment]
@thinkyhead this may be a duplicate of #3375.

**Comment by thinkyhead** [comment]
This one is probably fixed by #3388. But #3375 has some additional features that need a closer look.

**Comment by fbarcenas** [comment]
In my case the problem continue with the last rcbugfix

**Comment by jlcdi** [comment]
@thinkyhead I will give it a try. But, how to download the RCBugFix ? I can find many files, but I do not see the configuration.h. Which files shall I use to test the last RCBugFix ? Is there a complete package I can download and compile at a given moment ?

**Comment by ghost** [comment]
@jlcdi, link of newest RCBugFix complete package is here.
![marlinfirmware_marlin at rcbugfix - github_com_marlinfirmware_marlin_tree_rcbugf - 027](https://cloud.githubusercontent.com/assets/15308844/14290674/ed483ee0-fb9a-11e5-9e59-4776b63101c7.png)
link to RCBugFix page:
https://github.com/MarlinFirmware/Marlin/tree/RCBugFix
direct link of newest RCBugFix complete package:
https://github.com/MarlinFirmware/Marlin/archive/RCBugFix.zip

**Comment by jlcdi** [comment]
@esenapaj

Understood !!!

Thks a lot.

2016-04-05 23:58 GMT+07:00 esenapaj notifications@github.com:

**Comment by jlcdi** [comment]
@thinkyhead

Just tried with the newest RCBugFix.

It is the same.

When in "Move X", no line of menu appears to go back. We have to wait the effect of the temporisation to bring us back to the main menu. Same for Y....

**Comment by thinkyhead** [comment]
Sorry about the slow resolution. I'm still looking into this behavior. Let me look into it closer and maybe I will have some better questions and ideas to help figure this out.

**Comment by ghost** [comment]
@jlcdi, the problem was fixed by @thinkyhead a while ago.
Please try to newest RCBugFix.

**Comment by jlcdi** [comment]
@esenapaj
@thinkyhead
I confirm that this issue is still present with the last version of RCBugFix, downloaded 8 hours ago.

**Comment by ghost** [comment]
Well, fixing was done about 4 hours ago...

**Comment by thinkyhead** [comment]
@jlcdi Sadly, I only have internet access for a few hours a day right now. So I'm doing a lot of "hit and run" posting of fixes. Hopefully I will have better access soon and be more available in more time-zones.

**Comment by jlcdi** [comment]
@thinkyhead You are already doing great. I just tested with the last updated version (30 mns ago). Issue is still there.

**Comment by fbarcenas** [comment]
i check with the last `RCBUGFIX` and everything is correct and solved!

**Comment by thinkyhead** [comment]
Good news. I think it was fixed with the addition of clicky sounds. In the long run, this will be addressed in a better way (by implementing a proper "debounce" for LCD clicks). In the meantime, clicky sounds and the associated delay seem to do the trick!
