### ISSUE TITLE
Dual_X_Carriage not respecting soft Z max value 

### ISSUE THREAD

**Issue by AndrewDiehl** [MarlinFirmware/Marlin#4695]
Homing machine to Z max value (z=300)

Issue a M605 S1 to put in autopark mode

When changing from T0 to T1 and back, the Z lift exceeds the Zmax value and crashes the end stop into the top of the machine.

**Comment by thinkyhead** [comment]
Probably this use-case was simply never considered. We'll have to fix it.

**Comment by boelle** [comment]
@thinkyhead will this one be fixed in next rcbugfix?

**Comment by thinkyhead** [comment]
The "next RCBugFix" was 10 minutes ago as I added a few cleanup commits. I have a few other fish to fry before I get to work on this specific issue.

Anyway, once I find some time to work on it, with testing help from @AndrewDiehl I'm sure we'll have this tackled in no time.

**Comment by boelle** [comment]
@thinkyhead think there will be time for this old one?

**Comment by thinkyhead** [comment]
This should now be fixed in `RCBugFix` with the merger of the above PR. Please confirm, @AndrewDiehl, when you have a chance.

**Comment by AndrewDiehl** [comment]
@thinkyhead 

Finally got everything updated and tested. Same issue persists. 

I am around most of the day. I can do google hangouts using landru (plus) the (plus) great @ gmail . com or you can call 610-295-7867. For voice I may have to call back using wi-fi since my house has poor signal.

**Comment by thinkyhead** [comment]
@AndrewDiehl Oops. I applied the fix for `tool_change` but not for `G28`.
I'm adding the patch for this to #5175.

**Comment by thinkyhead** [comment]
@AndrewDiehl I'll try and reach you over the weekend some time. It will be good to get these Dual-X issues finally cleared and foist RC8 onto the world.

**Comment by thinkyhead** [comment]
@AndrewDiehl Concerning the duplication mode behavior. Does my PR make it worse? Or is it just as bad without it?

**Comment by AndrewDiehl** [comment]
Current behavior on duplication mode:

M605 S2 //nothing happens
T0 behaves as it would under the M605 S0 mode
Call T1, behaves like it would under M605 S0 mode
Call T0 again, heads are linked together, but not at the set distance apart.

**Comment by AndrewDiehl** [comment]
Nevermind, I forgot to home after calling the M605 S2. Seems to be working correctly.

**Comment by boelle** [comment]
@AndrewDiehl so this one and https://github.com/MarlinFirmware/Marlin/issues/4694 is solved?

**Comment by landodragon141** [comment]
@thinkyhead Is this one resolved?
Actually I'm a little bit confused what exactly isn't working at this point?

**Comment by thinkyhead** [comment]
This is resolved in a PR that hasn't been merged yet.

**Comment by thinkyhead** [comment]
Actually, yes. The main issue in this is resolved. Some of the other things later added are not.

**Comment by thinkyhead** [comment]
Actually, yes. The main issue in this is resolved. Some of the other things later added are not. The notes on PR #5175 indicate what I **_tried_** to resolve. The Duplication Mode issue may not actually exist, _**except**_ in that PR — i.e., something I changed while trying to fix one thing might have broken it. (You can see why I'm hesitant to touch this code when you look at it. It's not very well organized or documented. In fact, _documenting_ it liberally with comments would be a useful first step.)
